services:
  database:
    build: ./db
    container_name: postgres-container
    restart: always
    environment:
      POSTGRES_DB: grupo1
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - 5432

  app:
    build: .
    container_name: grupo1-app
    ports:
      - "${EXT_PORT}:3000"
    depends_on:
      - database
    env_file:
      - .env

volumes:
  postgres_data:
